name: base_app_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# build by specifying --build-name and --build-number, respectively.
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5

  url_launcher: ^6.1.2

  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.0

  hive: ^2.2.1
  hive_flutter: ^1.1.0
  
  logger: ^1.1.0
  dartz: ^0.10.1
  connectivity: ^3.0.6
  tiengviet: ^0.5.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/flags/
    - lib/common/country_code/i18n/af_i18n.json
    - lib/common/country_code/i18n/am_i18n.json
    - lib/common/country_code/i18n/ar_i18n.json
    - lib/common/country_code/i18n/az_i18n.json
    - lib/common/country_code/i18n/be_i18n.json
    - lib/common/country_code/i18n/bg_i18n.json
    - lib/common/country_code/i18n/bn_i18n.json
    - lib/common/country_code/i18n/bs_i18n.json
    - lib/common/country_code/i18n/ca_i18n.json
    - lib/common/country_code/i18n/cs_i18n.json
    - lib/common/country_code/i18n/da_i18n.json
    - lib/common/country_code/i18n/de_i18n.json
    - lib/common/country_code/i18n/el_i18n.json
    - lib/common/country_code/i18n/en_i18n.json
    - lib/common/country_code/i18n/es_i18n.json
    - lib/common/country_code/i18n/et_i18n.json
    - lib/common/country_code/i18n/fa_i18n.json
    - lib/common/country_code/i18n/fi_i18n.json
    - lib/common/country_code/i18n/fr_i18n.json
    - lib/common/country_code/i18n/gl_i18n.json
    - lib/common/country_code/i18n/ha_i18n.json
    - lib/common/country_code/i18n/he_i18n.json
    - lib/common/country_code/i18n/hi_i18n.json
    - lib/common/country_code/i18n/hr_i18n.json
    - lib/common/country_code/i18n/hu_i18n.json
    - lib/common/country_code/i18n/hy_i18n.json
    - lib/common/country_code/i18n/id_i18n.json
    - lib/common/country_code/i18n/is_i18n.json
    - lib/common/country_code/i18n/it_i18n.json
    - lib/common/country_code/i18n/ja_i18n.json
    - lib/common/country_code/i18n/ka_i18n.json
    - lib/common/country_code/i18n/kk_i18n.json
    - lib/common/country_code/i18n/km_i18n.json
    - lib/common/country_code/i18n/ko_i18n.json
    - lib/common/country_code/i18n/ku_i18n.json
    - lib/common/country_code/i18n/ky_i18n.json
    - lib/common/country_code/i18n/lt_i18n.json
    - lib/common/country_code/i18n/lv_i18n.json
    - lib/common/country_code/i18n/mk_i18n.json
    - lib/common/country_code/i18n/ml_i18n.json
    - lib/common/country_code/i18n/mn_i18n.json
    - lib/common/country_code/i18n/ms_i18n.json
    - lib/common/country_code/i18n/nb_i18n.json
    - lib/common/country_code/i18n/nl_i18n.json
    - lib/common/country_code/i18n/nn_i18n.json
    - lib/common/country_code/i18n/no_i18n.json
    - lib/common/country_code/i18n/pl_i18n.json
    - lib/common/country_code/i18n/ps_i18n.json
    - lib/common/country_code/i18n/pt_i18n.json
    - lib/common/country_code/i18n/ro_i18n.json
    - lib/common/country_code/i18n/ru_i18n.json
    - lib/common/country_code/i18n/sd_i18n.json
    - lib/common/country_code/i18n/sk_i18n.json
    - lib/common/country_code/i18n/sl_i18n.json
    - lib/common/country_code/i18n/so_i18n.json
    - lib/common/country_code/i18n/sq_i18n.json
    - lib/common/country_code/i18n/sr_i18n.json
    - lib/common/country_code/i18n/sv_i18n.json
    - lib/common/country_code/i18n/ta_i18n.json
    - lib/common/country_code/i18n/tg_i18n.json
    - lib/common/country_code/i18n/th_i18n.json
    - lib/common/country_code/i18n/tr_i18n.json
    - lib/common/country_code/i18n/tt_i18n.json
    - lib/common/country_code/i18n/ug_i18n.json
    - lib/common/country_code/i18n/uk_i18n.json
    - lib/common/country_code/i18n/ur_i18n.json
    - lib/common/country_code/i18n/uz_i18n.json
    - lib/common/country_code/i18n/vi_i18n.json
    - lib/common/country_code/i18n/zh_i18n.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Orbitron
      fonts:
        - asset: assets/fonts/orbitron/static/Orbitron-Regular.ttf
          weight: 400
        - asset: assets/fonts/orbitron/static/Orbitron-Medium.ttf
          weight: 500
        - asset: assets/fonts/orbitron/static/Orbitron-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/orbitron/static/Orbitron-Bold.ttf
          weight: 700
        - asset: assets/fonts/orbitron/static/Orbitron-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/orbitron/static/Orbitron-Black.ttf
          weight: 900

# https://pub.dev/packages/flutter_gen
# fluttergen -c pubspec.yaml
flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

# Generate Locales File:
# get generate locales lib/config/translations