name: base_app_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# build by specifying --build-name and --build-number, respectively.
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  get: 4.6.5
  url_launcher: 6.1.7
  flutter_svg: 1.1.6
  cached_network_image: 3.2.1
  hive: 2.2.3
  hive_flutter: 1.1.0
  logger: 1.1.0
  dartz: 0.10.1
  connectivity: 3.0.6
  tiengviet: 0.5.0
  equatable: 2.0.5
  pull_to_refresh: 2.0.0
  outline_gradient_button: 2.0.0+1
  intl: 0.17.0
  dio: 4.0.6
  path_provider: 2.0.11
  permission_handler: 10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: 2.0.0
  build_runner: 2.3.2
  
  flutter_lints: 2.0.1


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/flags/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Orbitron
      fonts:
        - asset: assets/fonts/orbitron/static/Orbitron-Regular.ttf
          weight: 400
        - asset: assets/fonts/orbitron/static/Orbitron-Medium.ttf
          weight: 500
        - asset: assets/fonts/orbitron/static/Orbitron-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/orbitron/static/Orbitron-Bold.ttf
          weight: 700
        - asset: assets/fonts/orbitron/static/Orbitron-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/orbitron/static/Orbitron-Black.ttf
          weight: 900

# https://pub.dev/packages/flutter_gen
# fluttergen -c pubspec.yaml
flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

# Generate Locales File:
# get generate locales lib/config/translations